from examples.baselines.diffusion_policy.diffusion_policy.encoders.plain_conv import PlainConv
from examples.baselines.diffusion_policy.diffusion_policy.encoders.clip import CLIPEncoder
from examples.baselines.diffusion_policy.diffusion_policy.encoders.dinov2 import DINOv2Encoder
from examples.baselines.diffusion_policy.diffusion_policy.encoders.resnet import ResNetEncoder