from diffusion_policy.encoders.plain_conv import PlainConv
from diffusion_policy.encoders.clip import CLIPEncoder
from diffusion_policy.encoders.dinov2 import DINOv2Encoder
from diffusion_policy.encoders.resnet import ResNetEncoder