# Position Controllers ---------------------------------------
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_thumb_1_joint
    - left_thumb_2_joint
    - left_index_1_joint
    - left_middle_1_joint
    - left_ring_1_joint
    - left_little_1_joint
    
    
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    left_thumb_1_joint: {trajectory: 0.2, goal: 0.2}
    left_thumb_2_joint: {trajectory: 0.2, goal: 0.2}
    left_index_1_joint: {trajectory: 0.2, goal: 0.2}
    left_middle_1_joint: {trajectory: 0.2, goal: 0.2}
    left_ring_1_joint: {trajectory: 0.2, goal: 0.2}
    left_little_1_joint: {trajectory: 0.2, goal: 0.2}
    
  stop_trajectory_duration: 0.5
  state_publish_rate:  500
  action_monitor_rate: 10


